site_name: Esi\Utility
site_description: 'Documentation for Utility - A Collection of various PHP utility functions.'
site_author: 'Eric Sizemore'
copyright: 'Copyright (C) 2017 - 2026 Eric Sizemore'
site_url: https://www.secondversion.com/docs/utility
docs_dir: docs/
repo_name: 'ericsizemore/utility'
repo_url: 'https://github.com/ericsizemore/utility'
theme: readthedocs
validation:
  anchors: warn
nav:
  - Home: index.md
  - Installing: installation.md
  - Basic Usage: basic-usage.md
  - Classes:
    - Array: arrays.md
    - Conversion: conversion.md
    - Date: dates.md
    - Environment: environment.md
    - Filesystem: filesystem.md
    - Image: image.md
    - Number: numbers.md
    - String: strings.md
  - Development:
    - 'Backward Compatibility': backward-compatibility.md
    - 'Code of Conduct': code-of-conduct.md
    - Contributing: contributing.md
    - License: license.md
    - Security: security.md
